---
title: "lumen_order_by_T4_niche_proportion"
author: "Ruqian Lyu"
date: "2024-07-31"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
suppressPackageStartupMessages({
  library(scater)
  library(ggplot2)
  library(mclust)
  library(slingshot)
  library(tradeSeq)
  library(grDevices)
  library(RColorBrewer)
  library(ComplexHeatmap)
  library(dplyr)
  library(Seurat)
  library(data.table)
})


```

```{r}

lumen_cell_types_sce <- readRDS(file="output/savedRDS/revisions2024/lumen_cell_types_sce.all.ct.rds")
dim(lumen_cell_types_sce)

```

```{r}
test_celltypes <- names(rowSums(assay(lumen_cell_types_sce,"final_CT_count")>=3) >=10)[rowSums(assay(lumen_cell_types_sce,"final_CT_count")>=3) >=10]
length(test_celltypes)
```

## Celltype proportions in sample groups

```{r,fig.width=12,fig.height=6}

lumen_cell_types_sce$sample_affect <-
  factor(lumen_cell_types_sce$sample_affect,
         levels = c("Unaffected","Less Affected",
                    "More Affected"))

sample_level <- unique(data.frame(lumen_cell_types_sce$sample,
                                  lumen_cell_types_sce$percent_pathology))

sample_level <- sample_level$lumen_cell_types_sce.sample[order(sample_level$lumen_cell_types_sce.percent_pathology)]
lumen_cell_types_sce$sample <- factor(lumen_cell_types_sce$sample,levels = sample_level)



lumen_cell_types_sce$sample_type <-
  factor(lumen_cell_types_sce$sample_type,levels = c("Unaffected","LF","MF","INT"))

plotDots(lumen_cell_types_sce,features = rownames(lumen_cell_types_sce),
         exprs_values = "final_CT_prop",group = "sample_affect")+
plotDots(lumen_cell_types_sce,features = rownames(lumen_cell_types_sce),
         exprs_values = "final_CT_prop",group = "sample_type")

plotColData(lumen_cell_types_sce,x = "sample_affect", y ="percent_pathology")+
  plotColData(lumen_cell_types_sce,x = "sample_type", y ="percent_pathology")
  

```

## Using transcripts assigned in cells in T4 niche

order by `pseudotime_rank_trans_t4_tie_avg`  

```{r}
lumen_order_by_t4 <- readr::read_csv("analysis/revision_2024/lumen_order_t4/pseudotime_by_niche_073024/lumen_metadata_niche_pseudotimes_073024.csv")
lumen_order_by_t4 %>% ggplot()+geom_point(mapping = 
                                            aes(x = pseudotime_rank_trans_t4_tie_avg,
                                                y= sample_affect))
```

```{r}
lumen_order_by_t4 %>% ggplot()+geom_point(mapping = 
                                            aes(x = pseudotime_rank_trans_t4_tie_avg,
                                                y = num_cells_lumen))
```

```{r}
lumen_order_by_t4 <- data.frame(lumen_order_by_t4)
rownames(lumen_order_by_t4) <- lumen_order_by_t4$lumen_id
lumen_cell_types_sce$pseudotime_rank_trans_t4_tie_avg <- lumen_order_by_t4[colnames(lumen_cell_types_sce),
                                                                           "pseudotime_rank_trans_t4_tie_avg"]

```


### CT changes along pseudotime order

```{r}
set.seed(100)
# evaluateK(
#   counts =
#     assays(lumen_cell_types_sce)[["final_CT_count"]],
#   family = "nb",
#   k = 8:15,
#   nGenes = 30,
#   cellWeights =matrix(1,nrow = ncol(lumen_cell_types_sce)), 
#   pseudotime = lumen_cell_types_sce$pseudotime_rank_trans_t4_tie_avg,
#   offset = log(lumen_cell_types_sce$num_cells_lumen))
```

```{r}

lumen_cell_types_sce_t4_ts <- fitGAM(counts =
                                       assays(lumen_cell_types_sce)[["final_CT_count"]],
                                  # sds = lumen_cell_types_sce_prop_PCA13$slingshot, 
                                  family = "nb",
                                  nknots = 12,
                                  genes = test_celltypes,
                                  cellWeights = matrix(1,nrow = ncol(lumen_cell_types_sce)), 
                                  pseudotime = lumen_cell_types_sce$pseudotime_rank_trans_t4_tie_avg,
                                  offset = log(lumen_cell_types_sce$num_cells_lumen))


predicted_expr_along_time <- function(models = lumen_nuclei_RNA_sce_ts_knot13,
                                      genes,
                                      sce,
                                  scale = TRUE){
  predicted_gene_expr_lumen <- data.frame(predictCells(models = models, 
                                                       gene = genes))
  
  
  predicted_gene_expr_lumen_size_normed <- apply(predicted_gene_expr_lumen,1,
                                                 function(x){
    log(x)-log(sce[,colnames(predicted_gene_expr_lumen)]$num_cells_lumen) 
  })
  if(scale){
      predicted_gene_expr_lumen_size_normed <- scale(predicted_gene_expr_lumen_size_normed)
  } 
  
  predicted_gene_expr_lumen_size_normed_zscore_time_order <- 
    predicted_gene_expr_lumen_size_normed[order(models$crv[,1]),]
  
  return(predicted_gene_expr_lumen_size_normed_zscore_time_order)
}


```



### CT change Heatmap


```{r}
lumen_cell_types_sce_t4_m <- 
  predicted_expr_along_time(sce = lumen_cell_types_sce,
                          models = lumen_cell_types_sce_t4_ts,
                          genes = test_celltypes)

order_feature_by_peak <- function(lumen_by_feature,windowsize = 50){
  gene_by_lumen <- t(lumen_by_feature)
  rollmean_gene <- frollmean(as.data.table(lumen_by_feature), 
                             windowsize,algo = "exact")
  
  gene_rank <- lapply(rollmean_gene, 
                      function(x) which.max(x[windowsize:length(x)]))
  
  gene_rank <- unlist(gene_rank)
  
  names(gene_rank) <- colnames(lumen_by_feature)
  gene_order_smooth <- names(gene_rank)[order(gene_rank)]
  gene_order_smooth
}

```

```{r}

order_ct_by_peak <- order_feature_by_peak(lumen_cell_types_sce_t4_m,50)
ct_ht <- Heatmap(t(lumen_cell_types_sce_t4_m)[order_ct_by_peak,],
        cluster_rows = FALSE,
        cluster_columns = FALSE,
        show_column_names = FALSE,
        name = "Celltype z-scored")
ct_ht
order_ct_by_peak <- order_feature_by_peak(lumen_cell_types_sce_t4_m,10)
ct_ht <- Heatmap(t(lumen_cell_types_sce_t4_m)[order_ct_by_peak,],
        cluster_rows = FALSE,
        cluster_columns = FALSE,
        show_column_names = FALSE,
        row_names_gp = gpar(fontsize=6),
        name= "Celltype z-scored")
ct_ht

```


```{r}
# Define range and parameters
start <- 1
end <- 1747
bin_size <- 10
step_size <- 5
# Load necessary library
library(dplyr)

# Define a sample data frame
data <- data.frame(
  time = start:end,
  value = start:end
)

# Define the rolling window size and step size
window_size <- 10
step_size <- 5

# Function to apply rolling window
rolling_window_df <- function(x, window_size, step_size) {
  result <- list()
  actual_bins <- seq(1, length(x) - window_size + 1, by = step_size) 
  for (i in actual_bins) {
    windowed_value <- x[i:(i + window_size - 1)]
    result[[length(result) + 1]] <- mean(windowed_value)
  }
  return(unlist(result))
}

# Apply rolling window
#result_df <- rolling_window_df(data, window_size, step_size)

```




```{r}
saveRDS(lumen_cell_types_sce, "analysis/revision_2024/lumen_order_t4/lumen_cell_types_sce_t4_ordered.rds")
saveRDS(lumen_cell_types_sce_t4_ts, "analysis/revision_2024/lumen_order_t4/lumen_cell_types_sce_t4_tradeseq.rds")

```


